sudo: required
dist: trusty
language: node_js
cache: yarn
branches:
  only:
  - source
node_js:
  - stable
before_install:
  - openssl aes-256-cbc -K $encrypted_2510e7b7233a_key -iv $encrypted_2510e7b7233a_iv -in .deploy-key.tgz.enc -out .deploy-key.tgz -d
  - tar -xzvf ./.deploy-key.tgz
script:
  - yarn build
  - chmod 600 ./.deploy-key/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ./.deploy-key/id_rsa
  - git config --global user.email "travis-ci@meth.app"
  - git config --global user.name "Travis CI"
  - yarn deploy
